# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo 2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo 2
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SVProgressHUD'
  pod 'DropDown'
  pod 'SideMenuSwift'
  pod 'Appirater'
  pod 'AFDateHelper'
  pod 'SwiftValidators'
#  pod 'RealmSwift'
  pod 'SDWebImage'
  pod 'Charts'
  pod 'Localize-Swift'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'LabelSwitch'
  pod 'UINavigationItem+Margin'
  pod 'ReachabilitySwift'
  pod 'OTPFieldView'
  pod 'SwiftyStoreKit'
end
